---
galaxy_info:
  author: Prakhar Srivastava
  description: Validation role for MCP with OpenShift workshop
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - openshift
    - validation
    - mcp
    - workshop

dependencies: []
