---
galaxy_info:
  role_name: ocp4_workload_register_sno
  author: Red Hat, Wolfgang Kulhanek (wkulhane@redhat.com)
  description: |
    Register a SNO cluster on RHACM
  license: MIT
  min_ansible_version: "2.9"
  platforms:
  - linux
  galaxy_tags:
  - ocp
  - openshift
dependencies: []
