---
# ------------------------------------------------
# Set up environment for the MCP Demo/Lab
# ------------------------------------------------
ocp4_workload_mcp_num_users: 2
ocp4_workload_mcp_user_base: user

ocp4_workload_mcp_gitops_repo: https://github.com/rhpds/mcp_gitops
ocp4_workload_mcp_gitops_repo_tag: main
ocp4_workload_mcp_openshift_repo_path: helm/mcp-openshift

ocp4_workload_mcp_openshift_namespace_base: mcp
ocp4_workload_mcp_openshift_image: quay.io/containers/kubernetes_mcp_server:latest



ocp4_workload_mcp_gitea_repo_path: helm/mcp-gitea
ocp4_workload_mcp_gitea_namespace_base: mcp
# Gitea user should be created by the Gitea Operator workload
ocp4_workload_mcp_gitea_image: docker.gitea.com/gitea-mcp-server:latest
ocp4_workload_mcp_gitea_name: gitea
ocp4_workload_mcp_gitea_namespace: gitea
ocp4_workload_mcp_gitea_external_url: https://gitea.apps.mcp-gm8rr.dynamic.redhatworkshops.io
ocp4_workload_mcp_gitea_internal_url: "http://{{ ocp4_workload_mcp_gitea_name }}.{{ ocp4_workload_mcp_gitea_namespace }}.svc:3000"
ocp4_workload_mcp_gitea_repository: mcp
ocp4_workload_mcp_gitea_user_base: "{{ ocp4_workload_mcp_user_base }}"
ocp4_workload_mcp_gitea_user_password: ""



ocp4_workload_mcp_librechat_namespace_base: librechat
ocp4_workload_mcp_librechat_repo: https://github.com/danny-avila/LibreChat
ocp4_workload_mcp_librechat_repo_tag: v0.8.1-rc2
ocp4_workload_mcp_librechat_repo_path: ./helm/librechat
# Set from secrets/vaults
ocp4_workload_mcp_librechat_litemaas_key: ""
ocp4_workload_mcp_librechat_litemaas_url: https://litellm.apps.maas.redhatworkshops.io/v1
ocp4_workload_mcp_librechat_litemaas_models: ["granite-3-2-8b-instruct", "granite-8b-code-instruct-128k", "mistral-7b-instruct", "codellama-7b","Llama-Guard-3-1B"]

ocp4_workload_mcp_librechat_user: "{{ ocp4_workload_mcp_user }}"
ocp4_workload_mcp_librechat_email: "{{ ocp4_workload_mcp_user }}@example.com"
# Set from secrets/vaults
ocp4_workload_mcp_librechat_password: ""

ocp4_workload_mcp_agent_namespace_base: agent
